=== maxsel/java_training/XMLstuff/data/taxi_station.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/taxistation"
        xmlns:tns="http://www.example.com/taxistation"
        elementFormDefault="qualified">

    <element name="taxi-station">
        <complexType>
            <sequence>
                <element ref="tns:car" minOccurs="2" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <element name="transport" type="tns:Transport" abstract="true"/>
    <element name="car" type="tns:Car" substitutionGroup="tns:transport" abstract="true"/>
    <element name="taxi" type="tns:Taxi" substitutionGroup="tns:car" />
    <element name="taxi-lorry" type="tns:TaxiLorry" substitutionGroup="tns:car"/>
    <element name="minibus" type="tns:Minibus" substitutionGroup="tns:car"/>
    <element name="trailer-car" type="tns:TrailerCar" substitutionGroup="tns:car"/>
    <element name="trailer" type="tns:Trailer" substitutionGroup="tns:transport"/>

    <complexType name="Transport">
        <sequence>
            <element name="reg-id" type="tns:LicenseId" />
            <element name="make" type="string" />
            <element name="model" type="string" />
            <element name="year" type="positiveInteger" />
            <element name="cost" type="positiveInteger" />
        </sequence>
    </complexType>

    <complexType name="Car">
        <complexContent>
            <extension base="tns:Transport">
                <sequence>
                    <element name="driver" type="string" />
                    <element name="fuel-consumption" type="positiveInteger" />
                    <element name="seats-number" type="positiveInteger" />
                    <element name="max-weight" type="positiveInteger" />
                    <element name="licence-type">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="DrivingLicenceType.A"/>
                                <enumeration value="DrivingLicenceType.B"/>
                                <enumeration value="DrivingLicenceType.C"/>
                                <enumeration value="DrivingLicenceType.D"/>
                                <enumeration value="DrivingLicenceType.BE"/>
                                <enumeration value="DrivingLicenceType.CE"/>
                                <enumeration value="DrivingLicenceType.DE"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Taxi">
        <complexContent>
            <extension base="tns:Car">
                <sequence>
                    <element name="price-km" type="positiveInteger" />
                </sequence>
                <attribute name="taxi-id" type="tns:IdType"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="TaxiLorry">
        <complexContent>
            <extension base="tns:Car">
                <sequence>
                    <element name="max-height" type="positiveInteger" />
                    <element name="price-hour" type="positiveInteger" />
                </sequence>
                <attribute name="taxi-lorry-id" type="tns:IdType"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Minibus">
        <complexContent>
            <extension base="tns:Car">
                <sequence>
                    <element name="price-hour" type="positiveInteger" />
                </sequence>
                <attribute name="minibus-id" type="tns:IdType"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Trailer">
        <complexContent>
            <extension base="tns:Transport">
                <sequence>
                    <element name="max-weight" type="positiveInteger" />
                    <element name="price-hour" type="positiveInteger" />
                </sequence>
                <attribute name="trailer-id" type="tns:IdType"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="TrailerCar">
        <complexContent>
            <extension base="tns:Car">
                <sequence>
                    <element name="price-hour" type="positiveInteger" />
                    <element name="trailer" type="tns:Trailer" />
                </sequence>
                <attribute name="trailer-car-id" type="tns:IdType"/>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="LicenseId">
        <restriction base="ID">
            <pattern value="([A-Z][A-Z])[0-9]{4}"/>
        </restriction>
    </simpleType>

    <simpleType name="IdType">
        <restriction base="ID">
            <pattern value="T[1-9][0-9]*"/>
        </restriction>
    </simpleType>
</schema>

=== maxsel/java_training/XMLstuff/data/taxi_station.xml
<taxi-station xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="http://www.example.com/taxistation"
             xsi:schemaLocation="http://www.example.com/taxistation taxi_station.xsd">
    <taxi taxi-id="T1">
        <!-- from transport -->
        <reg-id>AB1234</reg-id>
        <make>Ford</make>
        <model>Victoria</model>
        <year>2000</year>
        <cost>35000</cost>
        <!-- from car -->
        <driver>Vasya</driver>
        <fuel-consumption>4</fuel-consumption>
        <seats-number>4</seats-number>
        <max-weight>300</max-weight>
        <licence-type>DrivingLicenceType.B</licence-type>
        <!-- from taxi -->
        <price-km>300</price-km>
    </taxi>
    <taxi taxi-id="T9">
        <!-- from transport -->
        <reg-id>UV9805</reg-id>
        <make>Volkswagen</make>
        <model>Golf</model>
        <year>2005</year>
        <cost>40000</cost>
        <!-- from car -->
        <driver>Maxim</driver>
        <fuel-consumption>3</fuel-consumption>
        <seats-number>5</seats-number>
        <max-weight>200</max-weight>
        <licence-type>DrivingLicenceType.B</licence-type>
        <!-- from taxi -->
        <price-km>300</price-km>
    </taxi>
    <taxi taxi-id="T10">
        <!-- from transport -->
        <reg-id>PK4565</reg-id>
        <make>Volkswagen</make>
        <model>Passat</model>
        <year>2007</year>
        <cost>45000</cost>
        <!-- from car -->
        <driver>Igor</driver>
        <fuel-consumption>3</fuel-consumption>
        <seats-number>5</seats-number>
        <max-weight>200</max-weight>
        <licence-type>DrivingLicenceType.B</licence-type>
        <!-- from taxi -->
        <price-km>350</price-km>
    </taxi>
    <taxi-lorry taxi-lorry-id="T2">
        <!-- from transport -->
        <reg-id>RT5687</reg-id>
        <make>KAMAZ</make>
        <model>5320</model>
        <year>1995</year>
        <cost>100000</cost>
        <!-- from car -->
        <driver>Dimas</driver>
        <fuel-consumption>7</fuel-consumption>
        <seats-number>2</seats-number>
        <max-weight>10000</max-weight>
        <licence-type>DrivingLicenceType.C</licence-type>
        <!-- from taxiLorry -->
        <max-height>2</max-height>
        <price-hour>700</price-hour>
    </taxi-lorry>
    <minibus minibus-id="T3">
        <!-- from transport -->
        <reg-id>GH8462</reg-id>
        <make>Mercedes-Benz</make>
        <model>Minibus</model>
        <year>2002</year>
        <cost>50000</cost>
        <!-- from car -->
        <driver>Kolyan</driver>
        <fuel-consumption>5</fuel-consumption>
        <seats-number>25</seats-number>
        <max-weight>1000</max-weight>
        <licence-type>DrivingLicenceType.D</licence-type>
        <!-- from minibus -->
        <price-hour>500</price-hour>
    </minibus>

    <trailer-car trailer-car-id="T4">
        <!-- from transport -->
        <reg-id>RB1112</reg-id>
        <make>Lada</make>
        <model>Kalina</model>
        <year>2008</year>
        <cost>30000</cost>
        <!-- from car -->
        <driver>Alex</driver>
        <fuel-consumption>4</fuel-consumption>
        <seats-number>4</seats-number>
        <max-weight>750</max-weight>
        <licence-type>DrivingLicenceType.CE</licence-type>
        <!-- from trailerCar -->
        <price-hour>200</price-hour>
        <trailer trailer-id="T5">
            <!-- from transport -->
            <reg-id>TY5214</reg-id>
            <make>Lada</make>
            <model>Pricep</model>
            <year>2000</year>
            <cost>10000</cost>
            <!-- from trailer -->
            <max-weight>1000000</max-weight>
            <price-hour>100</price-hour>
        </trailer>
    </trailer-car>
</taxi-station>
